/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as celestialSbtSol from "./CelestialSBT.sol";
export type { celestialSbtSol };
import type * as identityRegistrySol from "./IdentityRegistry.sol";
export type { identityRegistrySol };
export type { CredentialVault } from "./CredentialVault";
export type { Groth16Verifier } from "./Groth16Verifier";
export type { IdentityRegistryProxy } from "./IdentityRegistryProxy";
