/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as celestialSbtSol from "./CelestialSBT.sol";
export * as identityRegistrySol from "./IdentityRegistry.sol";
export { CredentialVault__factory } from "./CredentialVault__factory";
export { Groth16Verifier__factory } from "./Groth16Verifier__factory";
export { IdentityRegistryProxy__factory } from "./IdentityRegistryProxy__factory";
