// SPDX-License-Identifier: MIT
// Meta Go — Hardhat deployment script
//
// Usage:
//   cd /app/contracts-hardhat
//   npm install
//   npx hardhat node            # in a separate terminal — local chain on :8545
//   npx hardhat run scripts/deploy.ts --network localhost
//
//   # for Polygon Amoy testnet:
//   export PRIVATE_KEY=0x...
//   export AMOY_RPC_URL=https://rpc-amoy.polygon.technology
//   npx hardhat run scripts/deploy.ts --network amoy
//
// After deployment, the script writes addresses to
//   /app/frontend/.env.local
// so the frontend automatically uses real contracts on next build.

import { ethers, network, artifacts } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log(`\n🚀 Meta Go — Contract Deployment`);
  console.log(`   Network:    ${network.name}`);
  console.log(`   Deployer:   ${deployer.address}`);
  console.log(`   Balance:    ${ethers.formatEther(await ethers.provider.getBalance(deployer.address))} ETH/MATIC\n`);

  // 1. Groth16Verifier
  console.log("→ Deploying Groth16Verifier...");
  const Verifier = await ethers.getContractFactory("Groth16Verifier");
  const verifier = await Verifier.deploy();
  await verifier.waitForDeployment();
  const verifierAddr = await verifier.getAddress();
  console.log(`   ✓ Groth16Verifier:   ${verifierAddr}`);

  // 2. IdentityRegistry
  console.log("→ Deploying IdentityRegistry Implementation (Primary)...");
  const Registry = await ethers.getContractFactory("IdentityRegistry");
  const registryImpl = await Registry.deploy();
  await registryImpl.waitForDeployment();
  const registryImplAddr = await registryImpl.getAddress();
  console.log(`   ✓ IdentityRegistry Impl: ${registryImplAddr}`);

  // Deploy proxy for Primary
  const registryInitData = Registry.interface.encodeFunctionData("initialize", [verifierAddr, deployer.address]);
  const Proxy = await ethers.getContractFactory("IdentityRegistryProxy");
  const registryProxy = await Proxy.deploy(registryImplAddr, registryInitData);
  await registryProxy.waitForDeployment();
  const registryAddr = await registryProxy.getAddress();
  console.log(`   ✓ IdentityRegistry Proxy:  ${registryAddr}`);

  // 2b. SecondaryRegistryBase
  console.log("→ Deploying SecondaryRegistryBase Proxy...");
  const registryBaseProxy = await Proxy.deploy(registryImplAddr, registryInitData);
  await registryBaseProxy.waitForDeployment();
  const registryBaseAddr = await registryBaseProxy.getAddress();
  console.log(`   ✓ SecondaryRegistryBase:  ${registryBaseAddr}`);

  // 2c. SecondaryRegistryArbitrum
  console.log("→ Deploying SecondaryRegistryArbitrum Proxy...");
  const registryArbProxy = await Proxy.deploy(registryImplAddr, registryInitData);
  await registryArbProxy.waitForDeployment();
  const registryArbAddr = await registryArbProxy.getAddress();
  console.log(`   ✓ SecondaryRegistryArbitrum:  ${registryArbAddr}`);

  // 3. CelestialSBT
  console.log("→ Deploying CelestialSBT...");
  const SBT = await ethers.getContractFactory("CelestialSBT");
  const sbt = await SBT.deploy();
  await sbt.waitForDeployment();
  const sbtAddr = await sbt.getAddress();
  console.log(`   ✓ CelestialSBT:      ${sbtAddr}`);

  // 4. CredentialVault
  console.log("→ Deploying CredentialVault...");
  const Vault = await ethers.getContractFactory("CredentialVault");
  const vault = await Vault.deploy();
  await vault.waitForDeployment();
  const vaultAddr = await vault.getAddress();
  console.log(`   ✓ CredentialVault:   ${vaultAddr}\n`);

  // Persist deployed addresses
  const out = {
    network: network.name,
    chainId: Number(network.config.chainId),
    deployer: deployer.address,
    deployedAt: new Date().toISOString(),
    contracts: {
      Groth16Verifier: verifierAddr,
      IdentityRegistry: registryAddr,
      SecondaryRegistryBase: registryBaseAddr,
      SecondaryRegistryArbitrum: registryArbAddr,
      CelestialSBT: sbtAddr,
      CredentialVault: vaultAddr,
    },
  };

  const outPath = path.join(__dirname, "..", "deployed-addresses.json");
  fs.writeFileSync(outPath, JSON.stringify(out, null, 2));
  console.log(`📝 Wrote ${outPath}`);

  // Update frontend env
  const envPath = path.join(__dirname, "..", "..", "frontend", ".env.local");
  const envContent = [
    `# Auto-generated by Meta Go deploy.ts on ${out.deployedAt}`,
    `NEXT_PUBLIC_IDENTITY_REGISTRY_ADDR=${registryAddr}`,
    `NEXT_PUBLIC_SECONDARY_REGISTRY_BASE_ADDR=${registryBaseAddr}`,
    `NEXT_PUBLIC_SECONDARY_REGISTRY_ARBITRUM_ADDR=${registryArbAddr}`,
    `NEXT_PUBLIC_SBT_ADDR=${sbtAddr}`,
    `NEXT_PUBLIC_VAULT_ADDR=${vaultAddr}`,
    `NEXT_PUBLIC_VERIFIER_ADDR=${verifierAddr}`,
    `NEXT_PUBLIC_DEFAULT_CHAIN_ID=${out.chainId}`,
    "",
  ].join("\n");
  fs.writeFileSync(envPath, envContent);
  console.log(`📝 Wrote ${envPath}\n`);

  console.log(`✅ Deployment complete. Rebuild frontend with:`);
  console.log(`   cd /app/frontend && yarn build && sudo supervisorctl restart frontend\n`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
