/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface CredentialVaultInterface extends Interface {
  getFunction(
    nameOrSignature: "issueCredential" | "revokeCredential" | "vault"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CredentialIssued" | "CredentialRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "issueCredential",
    values: [AddressLike, BytesLike, string, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeCredential",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vault",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "issueCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;
}

export namespace CredentialIssuedEvent {
  export type InputTuple = [
    holder: AddressLike,
    vcId: BytesLike,
    issuer: AddressLike
  ];
  export type OutputTuple = [holder: string, vcId: string, issuer: string];
  export interface OutputObject {
    holder: string;
    vcId: string;
    issuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CredentialRevokedEvent {
  export type InputTuple = [holder: AddressLike, vcId: BytesLike];
  export type OutputTuple = [holder: string, vcId: string];
  export interface OutputObject {
    holder: string;
    vcId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CredentialVault extends BaseContract {
  connect(runner?: ContractRunner | null): CredentialVault;
  waitForDeployment(): Promise<this>;

  interface: CredentialVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  issueCredential: TypedContractMethod<
    [
      holder: AddressLike,
      vcId: BytesLike,
      vcType: string,
      vcHash: BytesLike,
      ipfsURI: string
    ],
    [void],
    "nonpayable"
  >;

  revokeCredential: TypedContractMethod<
    [holder: AddressLike, vcId: BytesLike],
    [void],
    "nonpayable"
  >;

  vault: TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [
      [string, string, string, bigint, boolean, string] & {
        vcType: string;
        vcHash: string;
        ipfsURI: string;
        issuedAt: bigint;
        revoked: boolean;
        issuer: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "issueCredential"
  ): TypedContractMethod<
    [
      holder: AddressLike,
      vcId: BytesLike,
      vcType: string,
      vcHash: BytesLike,
      ipfsURI: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeCredential"
  ): TypedContractMethod<
    [holder: AddressLike, vcId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vault"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [
      [string, string, string, bigint, boolean, string] & {
        vcType: string;
        vcHash: string;
        ipfsURI: string;
        issuedAt: bigint;
        revoked: boolean;
        issuer: string;
      }
    ],
    "view"
  >;

  getEvent(
    key: "CredentialIssued"
  ): TypedContractEvent<
    CredentialIssuedEvent.InputTuple,
    CredentialIssuedEvent.OutputTuple,
    CredentialIssuedEvent.OutputObject
  >;
  getEvent(
    key: "CredentialRevoked"
  ): TypedContractEvent<
    CredentialRevokedEvent.InputTuple,
    CredentialRevokedEvent.OutputTuple,
    CredentialRevokedEvent.OutputObject
  >;

  filters: {
    "CredentialIssued(address,bytes32,address)": TypedContractEvent<
      CredentialIssuedEvent.InputTuple,
      CredentialIssuedEvent.OutputTuple,
      CredentialIssuedEvent.OutputObject
    >;
    CredentialIssued: TypedContractEvent<
      CredentialIssuedEvent.InputTuple,
      CredentialIssuedEvent.OutputTuple,
      CredentialIssuedEvent.OutputObject
    >;

    "CredentialRevoked(address,bytes32)": TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;
    CredentialRevoked: TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;
  };
}
