/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type {
  Groth16Verifier,
  Groth16VerifierInterface,
} from "../Groth16Verifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[2]",
        name: "_a",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[2][2]",
        name: "_b",
        type: "uint256[2][2]",
      },
      {
        internalType: "uint256[2]",
        name: "_c",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[4]",
        name: "_input",
        type: "uint256[4]",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561000f575f80fd5b506101118061001d5f395ff3fe6080604052348015600e575f80fd5b50600436106026575f3560e01c80635fe8c13b14602a575b5f80fd5b60396035366004608d565b604d565b604051901515815260200160405180910390f35b5f81351580159060605750602082013515155b95945050505050565b80604081018310156078575f80fd5b92915050565b80608081018310156078575f80fd5b5f805f80610180858703121560a0575f80fd5b60a886866069565b935060b58660408701607e565b925060c28660c087016069565b915060d0866101008701607e565b90509295919450925056fea26469706673582212207eb9e8081973ef919c3316b95fa984cb15f196f562cdaad9d59f69972395eac764736f6c63430008180033";

type Groth16VerifierConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: Groth16VerifierConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Groth16Verifier__factory extends ContractFactory {
  constructor(...args: Groth16VerifierConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Groth16Verifier & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Groth16Verifier__factory {
    return super.connect(runner) as Groth16Verifier__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): Groth16VerifierInterface {
    return new Interface(_abi) as Groth16VerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): Groth16Verifier {
    return new Contract(address, _abi, runner) as unknown as Groth16Verifier;
  }
}
