/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as identityRegistrySol from "./IdentityRegistry.sol";
export { CelestialSBT__factory } from "./CelestialSBT__factory";
export { CredentialVault__factory } from "./CredentialVault__factory";
export { Groth16Verifier__factory } from "./Groth16Verifier__factory";
